version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/cfssl"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/node"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/node-build"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/node-current"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/node-current-min"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/node-min"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/tinc"
    schedule:
      interval: "daily"
