name: Build Docker image
description: Build Docker image
inputs:
  name:
    required: true
    description: Directory and image name
  docker-login:
    required: true
    description: Docker username
  docker-password:
    required: true
    description: Docker password
runs:
  using: composite
  steps:
    # - name: Run hadolint
    #   uses: hadolint/hadolint-action@v1.6.0
    #   with:
    #     dockerfile: ${{ inputs.name }}/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2.6.0

    - name: Build Docker image
      uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
      with:
        context: ${{ inputs.name }}
        load: true
        pull: true
        push: false
        tags: "myrotvorets/${{ inputs.name }}:latest"

    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "myrotvorets/${{ inputs.name }}:latest"
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@004c5de30b6423267685b897a3d595e944f7fed5 # v2.20.2
      if: always()
      with:
        sarif_file: trivy-results.sarif

    - name: Login to DockerHub
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        username: ${{ inputs.docker-login }}
        password: ${{ inputs.docker-password }}
      if: github.event_name != 'push' || github.ref == 'refs/heads/master'

    - name: Push the image
      shell: bash
      run: |
        docker push "myrotvorets/${{ inputs.name }}:latest"
      if: ${{ github.event_name != 'push' || github.ref == 'refs/heads/master' }}
