name: Build Docker image
description: Build Docker image
inputs:
  name:
    required: true
    description: Directory and image name
  docker-login:
    required: true
    description: Docker username
  docker-password:
    required: true
    description: Docker password
runs:
  using: composite
  steps:
    # - name: Run hadolint
    #   uses: hadolint/hadolint-action@v1.6.0
    #   with:
    #     dockerfile: ${{ inputs.name }}/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

    - name: Build Docker image
      uses: docker/build-push-action@c382f710d39a5bb4e430307530a720f50c2d3318 # v6.0.0
      with:
        context: ${{ inputs.name }}
        load: true
        pull: true
        push: false
        tags: "myrotvorets/${{ inputs.name }}:latest"

    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "myrotvorets/${{ inputs.name }}:latest"
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10
      if: always()
      with:
        sarif_file: trivy-results.sarif

    - name: Login to DockerHub
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        username: ${{ inputs.docker-login }}
        password: ${{ inputs.docker-password }}
      if: github.event_name != 'push' || github.ref == 'refs/heads/master'

    - name: Push the image
      shell: bash
      run: |
        docker push "myrotvorets/${{ inputs.name }}:latest"
      if: ${{ github.event_name != 'push' || github.ref == 'refs/heads/master' }}
