name: Build Docker image
description: Build Docker image
inputs:
  name:
    required: true
    description: Directory and image name
  docker-login:
    required: true
    description: Docker username
  docker-password:
    required: true
    description: Docker password
runs:
  using: composite
  steps:
    # - name: Run hadolint
    #   uses: hadolint/hadolint-action@v1.6.0
    #   with:
    #     dockerfile: ${{ inputs.name }}/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

    - name: Build Docker image
      uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0 # tag=v3.1.0
      with:
        context: ${{ inputs.name }}
        load: true
        pull: true
        push: false
        tags: "myrotvorets/${{ inputs.name }}:latest"

    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "myrotvorets/${{ inputs.name }}:latest"
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2.1.16
      if: always()
      with:
        sarif_file: trivy-results.sarif

    - name: Login to DockerHub
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
      with:
        username: ${{ inputs.docker-login }}
        password: ${{ inputs.docker-password }}
      if: github.event_name != 'push' || github.ref == 'refs/heads/master'

    - name: Push the image
      shell: bash
      run: |
        docker push "myrotvorets/${{ inputs.name }}:latest"
      if: ${{ github.event_name != 'push' || github.ref == 'refs/heads/master' }}
