name: Build cfssl image

on:
  push:
    paths:
      - "cfssl/**"
      - ".github/workflows/cfssl.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2.4.0

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: cfssl
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
