name: Build cfssl image

on:
  push:
    paths:
      - "cfssl/**"
      - ".github/workflows/cfssl.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: cfssl
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
