name: Build kubectl-action image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 3 * * *"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2.4.0

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: kubectl-action
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
