name: Build kubectl-action image

on:
  push:
    paths:
      - "kubectl-action/**"
      - ".github/workflows/kubectl-action.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: kubectl-action
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
