name: Build node-min image

on:
  push:
    paths:
      - "node-min/**"
      - ".github/workflows/node-min.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: node-min
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
