name: Build openssl image

on:
  push:
    paths:
      - "openssl/**"
      - ".github/workflows/openssl.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # tag=v2.4.1

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: openssl
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
