name: Build tinc image

on:
  push:
    paths:
      - "tinc/**"
      - ".github/workflows/tinc.yml"
      - ".github/build-image-action/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Build image
        uses: ./.github/build-image-action
        with:
          name: tinc
          docker-login: ${{ secrets.DOCKER_LOGIN }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
